version: 2.1

orbs:
  node: circleci/node@4.0.1

jobs:
  prepare:
    steps:
      - checkout
      - run:
          name: Generate ember build
          command: ember build --environment=development --output-path=dist/website

workflows:
  build_and_test:
    jobs:
      - prepare
