---
version: 2

references:
  images:
    ember: &EMBER_IMAGE circleci/node:8-browsers
jobs:
  # build the ember js website
  ember-build:
    docker:
      - image: *EMBER_IMAGE
    steps:
      - checkout
      - run: /deploy-ui.sh