version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0
  
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: ./deploy.sh
      - aws-s3/sync:
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist/website
          to: 's3://209poker.com'
      - aws-s3/copy:
          from: bucket/index.html
          to: 's3://209poker.com'
